notifications:
  email: false

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
- docker pull $DOCKER_IMAGE

script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
- ls wheelhouse/

deploy:
  provider: pypi
  user: "MarkReedZ"
  password:
    secure: SPPy9bAXJSflzRfaGRDm5gSbV02v+TX1WASWXP9DgyrWg6jvkBs7b2+vVgaQuMRsLafZ1YUi0UM+eWPwn1OlmDC1eflSeGFDI3Sxk77CFbvqlG4sOetluup8TZZJQqOjG8exBhs+WsAHaNsXR8zlAuS/BAgeqcMIQl4g+JQUNfRcq3Q4KCyVBcE7pgLkL/lYHrNDqP+GWKYtCa8hV/EamNwCsGedh+0spPYoUSskt5LGey/8EbCwwgviJ27URfbOL4IvUPP4vrK7snZswp/J5NeQ7OHwE6VD0I+HbyzUgn3pLWatMiCD+U4keknaDWX25YFpkIkSB7+yB2R0JjSmZcV7rI6bog6PC/AXx5vjNs2FaUxgg27JOlkcC5Hfv4VuqYomoh3WmgNNYWvj5JXfQxcDd64KJwZDSX0h7EXD+rTeqI32qYSx8/rADJj0/Sdruys5cXr8FBpAdn9r9zSNgLgVMFEnTIvzTk4Lf7iubrDfYw9wDJ3g7g69i+HIhyUYyoxvIWOuoKxy/ZYRZZ1//VOdeiUM61qn6tNkxuDrKe9jgxgSnRvqwmkjqe7fV+NUoAEtcUFJyTV/Xx3T+b0vWSxE4cCXohaOMRRJH+7Zkzm3GuPaufv5s45jqRuUuGAo82GUOqFsxIgeWUXVkdacSLk/LK4PZyjiPy7W5KjoRaw=
