language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip3

env:
  global:
    - TWINE_USERNAME=MarkReedZ

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
