notifications:
  email: false

# Only build tags
#if: tag IS present

env:
  global:
    - TWINE_USERNAME=MarkReedZ

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
  - |
    #if [[ $TRAVIS_TAG ]]; then
      /opt/python/cp37-cp37m/bin/python -m pip install twine
      /opt/python/cp37-cp37m/bin/python -m twine upload wheelhouse/*.whl
    #fi
