deploy:
  - provider: Environment
    name: production
    on:
      APPVEYOR_REPO_TAG: true

environment:
  CIBW_BUILD: cp3?-*
  CIBW_SKIP: cp34-*

build_script:
  - pip install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload wheelhouse/*.whl
    )


artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
